[workspace]
members = [
    'sixtyfps_runtime/corelib',
    'sixtyfps_runtime/corelib_macros',
    'sixtyfps_runtime/interpreter',
    'sixtyfps_runtime/rendering_backends/gl',
    'sixtyfps_runtime/rendering_backends/qt',
    'sixtyfps_runtime/rendering_backends/default',
    'sixtyfps_compiler',
    'sixtyfps_compiler/parser_test_macro',
    'api/sixtyfps-rs',
    'api/sixtyfps-rs/sixtyfps-macros',
    'api/sixtyfps-rs/sixtyfps-build',
    'api/sixtyfps-node/native',
    'api/sixtyfps-wasm-interpreter',
    'tools/compiler',
    'tools/viewer',
    'tools/syntax_updater',
    'tools/lsp',
    'examples/gallery',
    'examples/printerdemo/rust',
    'examples/todo/rust',
    'examples/slide_puzzle',
    'examples/7gui',
    'examples/memory',
    'examples/rgb_slider',
    'helper_crates/const-field-offset',
    'helper_crates/vtable',
    'helper_crates/vtable/macro',
    'xtask',
    'tests/driver',
    'tests/driver_lib',
    'tests/rustdriver'
]

default-members = [
    'sixtyfps_runtime/corelib',
    'sixtyfps_runtime/interpreter',
    'sixtyfps_runtime/rendering_backends/gl',
    'sixtyfps_runtime/rendering_backends/qt',
    'sixtyfps_runtime/rendering_backends/default',
    'sixtyfps_compiler',
    'api/sixtyfps-rs',
    'api/sixtyfps-rs/sixtyfps-build',
    'api/sixtyfps-node/native',
    'tools/compiler',
    'tools/viewer',
    'tools/syntax_updater',
    'tools/lsp',
    'examples/gallery',
    'examples/printerdemo/rust',
    'examples/todo/rust',
    'examples/slide_puzzle',
    'tests/driver',
    'tests/rustdriver'
]

[profile.release]
lto = true
